#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 -m venv .venv
.venv/bin/pip3 install -r ./requirements.txt

.venv/bin/python3 -m flask run --port 8001 --host 0.0.0.0 --debug
#flask run  --port 8001 --host 0.0.0.0 --debug